from enum import Enum


class BlendModeKey(Enum):
    PASS_THROUGH = b"pass"
    NORMAL = b"norm"
    DISSOLVE = b"diss"
    DARKEN = b"dark"
    MULTIPLY = b"mul "
    COLOR_BURN = b"idiv"
    LINEAR_BURN = b"lbrn"
    DARKER_COLOR = b"dkCl"
    LIGHTEN = b"lite"
    SCREEN = b"scrn"
    COLOR_DODGE = b"div "
    LINEAR_DODGE = b"lddg"
    LIGHTER_COLOR = b"lgCl"
    OVERLAY = b"over"
    SOFT_LIGHT = b"sLit"
    HARD_LIGHT = b"hLit"
    VIVID_LIGHT = b"vLit"
    LINEAR_LIGHT = b"lLit"
    PIN_LIGHT = b"pLit"
    HARD_MIX = b"hMix"
    DIFFERENCE = b"diff"
    EXCLUSION = b"smud"
    SUBTRACT = b"fsub"
    DIVIDE = b"fdiv"
    HUE = b"hue "
    SATURATION = b"sat "
    COLOR = b"colr"
    LUMINOSITY = b"lum "
